<a href="https://colab.research.google.com/github/burrfer/introduccion-de-github/blob/main/puntos_digitales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
#Importamos las librerias necesarias
import pandas as pd
import numpy as np

In [13]:
df_PD = pd.read_csv('/content/drive/MyDrive/Diplomatura ccc/Evaluación Final/puntos_digitales.csv')

In [14]:
df_PD.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 661 entries, 0 to 660
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_pd                 661 non-null    int64
 1   nombre_pd             661 non-null    object
 2   direccion             661 non-null    object
 3   nombre_institucional  661 non-null    object
 4   id_provincia          661 non-null    object
 5   id_departamento       661 non-null    int64
 6   id_localidad          661 non-null    int64
 7   cod_bahra_localidad   661 non-null    int64
 8   id_municipio          661 non-null    object
 9   provincia             661 non-null    object
 10  departamento          661 non-null    object
 11  localidad             661 non-null    object
 12  municipio             661 non-null    object
 13  mail_institucional    597 non-null    object
 14  latitud               661 non-null    float64
 15  longitud              661 non-null    float64
 16  horarios              594 non-null    object
 17  link_facebook         138 non-null    object
 18  estado                661 non-null    object
dtypes: float64(2), int64(4), object(13)
memory usage: 98.2+ KB

In [15]:
df_PD.head(2)

,id_pd,nombre_pd,direccion,nombre_institucional,id_provincia,id_departamento,id_localidad,cod_bahra_localidad,id_municipio,provincia,departamento,localidad,municipio,mail_institucional,latitud,longitud,horarios,link_facebook,estado
0,40,Berisso I,33 S/N esquina 169 (Barrio Obrero),CIC,AR-B,1208,323,6098010004,BUE014,Buenos Aires,Berisso,Berisso,Berisso,berisso@puntodigital.gob.ar,-34.881902,-57.85778,"Lunes 08:00 a 17:00 , Martes 08:00 a 17:00 , M...",https://www.facebook.com/nac.berisso/?notif_t=...,Activo
1,41,Cañuelas,Mozotegui 807,Edificio Municipal,AR-B,1213,431,6134030000,BUE018,Buenos Aires,Cañuelas,Cañuelas,Cañuelas,canuelas@puntodigital.gob.ar,-35.049960,-58.76252,"Lunes 08:00 a 18:00 , Martes 08:00 a 18:00 , M...",https://www.facebook.com/Punto-Digital-Cañuela...,Activo

In [16]:
df_PD = df_PD[['provincia','departamento','localidad','nombre_pd','direccion','latitud','longitud',]]
df_PD.head(2)

,provincia,departamento,localidad,nombre_pd,direccion,latitud,longitud
0,Buenos Aires,Berisso,Berisso,Berisso I,33 S/N esquina 169 (Barrio Obrero),-34.881902,-57.85778
1,Buenos Aires,Cañuelas,Cañuelas,Cañuelas,Mozotegui 807,-35.049960,-58.76252

In [17]:
df_PD.loc[df_PD.loc[:, 'provincia'] == 'Buenos Aires'].head(2)

,provincia,departamento,localidad,nombre_pd,direccion,latitud,longitud
0,Buenos Aires,Berisso,Berisso,Berisso I,33 S/N esquina 169 (Barrio Obrero),-34.881902,-57.85778
1,Buenos Aires,Cañuelas,Cañuelas,Cañuelas,Mozotegui 807,-35.049960,-58.76252

In [18]:
df_PDBSAS = df_PD.loc[df_PD.loc[:, 'provincia'] == 'Buenos Aires']

In [19]:
df_PDBSAS.shape

(142, 7)

In [20]:
df_PDBSAS = df_PDBSAS.rename(columns={'departamento':'partido'})
df_PDBSAS.columns

Index(['provincia', 'partido', 'localidad', 'nombre_pd', 'direccion',
       'latitud', 'longitud'],
      dtype='object')

In [21]:
df_PDBSAS.loc[df_PDBSAS.loc[:, 'partido'] == 'Lanus']

,provincia,partido,localidad,nombre_pd,direccion,latitud,longitud
12,Buenos Aires,Lanus,Remedios Escalada de San Martin,Lanús I (Pupi),Monseñor Hladnik 3856,-34.715557,-58.417292
239,Buenos Aires,Lanus,Lanus Este,Lanús III (Velódromo),Córdoba 2300,-34.714971,-58.388110
281,Buenos Aires,Lanus,Lanus Oeste,Lanús IV (NIDO Jardín),Pje Aguirre,-34.677738,-58.434029
282,Buenos Aires,Lanus,Monte Chingolo,Lanús V (NIDO),Pitagoras 4550,-34.728690,-58.350705

In [22]:
df_PDBSAS.loc[df_PDBSAS.loc[:, 'partido'] == 'Almirante Brown']

,provincia,partido,localidad,nombre_pd,direccion,latitud,longitud
588,Buenos Aires,Almirante Brown,Glew,Almirante Brown,Garibaldi 220,-34.874579,-58.358651